import {ANALYSIS_CONTRACT, ANALYSIS_CARD_STATES, analysisCardPolicy, tradePriceLevels} from '../worker/contract.js';
import {methodologyRegistry} from '../worker/methodology.js';
const escapeHtml=value=>String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function renderMethodology(registry=methodologyRegistry()){
 const versions=Object.entries(registry.versions).map(([key,value])=>'<li>'+escapeHtml(key)+': <code>'+escapeHtml(value)+'</code></li>').join('');
 const rows=registry.reference.features.map(f=>'<tr><td>'+escapeHtml(f.label)+'</td><td>'+escapeHtml(f.formula)+'</td><td>'+escapeHtml(f.unit)+'<br>'+escapeHtml(f.priceBasis)+'<br>'+escapeHtml(f.source)+'<br>'+f.lookbackSessions+' Sitzungen; '+escapeHtml(f.availability)+'</td><td>'+f.weight*100+' %; '+escapeHtml(f.influence)+'</td><td>'+escapeHtml(f.scoreFormula)+'</td></tr>').join('');
 return '<p><b>Verwendet:</b> '+escapeHtml(registry.reference.score)+'. '+escapeHtml(registry.reference.outcome)+'. '+escapeHtml(registry.reference.selection)+'</p><details><summary>Aktive Versionen und fünf Referenzmerkmale</summary><ul>'+versions+'</ul><div class="table-wrap" tabindex="0" aria-label="Methodik und Einheiten"><table><thead><tr><th>Merkmal</th><th>Rohformel</th><th>Einheit</th><th>Referenzeinfluss</th><th>Teilscore</th></tr></thead><tbody>'+rows+'</tbody></table></div><p>C bezeichnet den letzten abgeschlossenen bereinigten Schlusskurs. Volatilität: 20 einfache tägliche Renditen, Stichprobenvarianz mit Teiler 19, Annualisierung √252. Die festen Referenzgewichte sind nicht statistisch optimiert.</p></details><p><b>Experimentell: '+escapeHtml(registry.versions.features)+'</b> · keine Änderung der Rangliste, keine Referenzgewichte. '+escapeHtml(registry.features.influence)+' '+escapeHtml(registry.features.outcomeWeights)+' '+escapeHtml(registry.features.qualification)+'</p><p><b>Experimentelle Diagnosen:</b> '+registry.diagnostics.items.map(escapeHtml).join('; ')+'. Kein Rankinggewicht.</p><p><b>Kalender:</b> '+escapeHtml(registry.calendar.description)+' '+escapeHtml(registry.calendar.access)+'</p><p>'+registry.limitations.map(escapeHtml).join(' · ')+'.</p>';
}
export function renderPage(html){
 if(!html.includes('__ANALYSIS_CONTRACT_JSON__'))throw Error('Analysis contract placeholder missing');
 return html.replace('__METHODOLOGY_HTML__',renderMethodology()).replace('__METHODOLOGY_PLANNED_HTML__','<section class="panel method-panel"><h2>Geplant · noch kein aktiver Renditekern</h2><ul>'+methodologyRegistry().planned.items.map(item=>'<li>'+escapeHtml(item)+'</li>').join('')+'</ul></section>').replace('__METHODOLOGY_JSON__',JSON.stringify(methodologyRegistry()).replace(/</g,'\\u003c')).replace('__ANALYSIS_CARD_POLICY__', 'const ANALYSIS_CARD_STATES='+JSON.stringify(ANALYSIS_CARD_STATES)+'; const tradePriceLevels='+tradePriceLevels.toString()+'; const analysisCardPolicy='+analysisCardPolicy.toString()+';').replace('__ANALYSIS_CONTRACT_JSON__',JSON.stringify(ANALYSIS_CONTRACT).replace(/</g,'\\u003c'));
}
