import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
const html=fs.readFileSync('app/index.html','utf8');
const ids=['broker-comparison','broker-tariff','broker-mode','broker-name','broker-status','cost-summary','open-broker','tab-settings','cost-settings','entryFeeBps','exitFeeBps','entryFixedFee','exitFixedFee','entrySlippageBps','exitSlippageBps','entrySpreadBps','exitSpreadBps'];
const nodes=Object.fromEntries(ids.map(id=>[id,{value:id==='broker-mode'?'default':'',disabled:false,textContent:'',addEventListener(){},focus(){},checkValidity(){return this.value!==''&&Number(this.value)>=0&&(!id.endsWith('Bps')||Number(this.value)<=1000)}}]));
let stored,refreshes=0;
const context=vm.createContext({el:id=>nodes[id],localStorage:{getItem:()=>null,setItem:(key,value)=>stored=JSON.parse(value)},refreshSimulation:()=>refreshes++,activateTab(){},safe:v=>String(v),Number,JSON,Object});
vm.runInContext(html.slice(html.indexOf('    const UI_BROKER_PROFILES='),html.indexOf('    function showQuality(')),context);
assert.equal(nodes.entryFeeBps.value,10);assert.equal(nodes.entrySlippageBps.disabled,true);
nodes['broker-mode'].value='custom';nodes['broker-name'].value='Mein Tarif';nodes.entryFixedFee.value=2;
vm.runInContext('updateCostProfile()',context);assert.equal(stored.costs.entryFixedFee,2);assert.equal(stored.name,'Mein Tarif');assert.equal(nodes.entryFeeBps.disabled,false);assert.match(nodes['cost-summary'].textContent,/Mein Tarif/);
nodes.entryFeeBps.value=-1;vm.runInContext('updateCostProfile()',context);assert.equal(stored.costs.entryFeeBps,10);assert.match(nodes['broker-status'].textContent,/Ungültige/);
nodes['broker-mode'].value='default';vm.runInContext('updateCostProfile()',context);assert.equal(stored.costs.entryFixedFee,0);assert.equal(nodes.entryFixedFee.disabled,true);
assert.equal(vm.runInContext("validCostProfile({mode:'custom',name:'x',costs:{entryFeeBps:Infinity}})",context),false);
assert.ok(refreshes>=4);
assert.ok(html.includes('id="view-settings"')&&html.includes('id="view-broker"'));
console.log('Broker profile checks passed: defaults, custom costs, persistence, invalid values, reset and automatic refresh.');

nodes['broker-mode'].value='ibkr-fixed';vm.runInContext('updateCostProfile()',context);assert.equal(stored.mode,'ibkr-fixed');assert.equal(nodes.entryFeeBps.value,0);assert.equal(nodes.entrySlippageBps.disabled,false);assert.match(nodes['broker-tariff'].innerHTML,/0,005/);
nodes['broker-mode'].value='tr-best';vm.runInContext('updateCostProfile()',context);assert.match(nodes['broker-tariff'].innerHTML,/EUR/);
const {BROKER_PROFILES,brokerBaseFee,simulateTrade}=await import('../worker/simulation.js');
assert.equal(brokerBaseFee('ibkr-fixed',100,100),1);assert.equal(brokerBaseFee('ibkr-fixed',1000,100),5);assert.equal(brokerBaseFee('ibkr-fixed',10,.2),.02);
assert.equal(brokerBaseFee('lynx-us',100,100),5);assert.equal(brokerBaseFee('lynx-us',1000,100),10);assert.equal(brokerBaseFee('captrader-us',100,100),2);
assert.throws(()=>brokerBaseFee('tr-best',100,100));
assert.equal(simulateTrade([],0,{}, {brokerProfile:'tr-best'}).status,'blocked');
const bars=Array.from({length:21},(_,i)=>({date:'2026-01-'+String(i+1).padStart(2,'0'),open:100,high:101,low:99,close:100}));
const result=simulateTrade(bars,0,{coverageVerified:true,pointInTimeVerified:true,splits:[],dividends:[]},{brokerProfile:'ibkr-fixed',strict:false,costs:{entrySlippageBps:0,exitSlippageBps:0,entryFeeBps:0,exitFeeBps:0}});
assert.equal(result.ledger[0].shares,99);assert.equal(result.totalFees,2);assert.equal(result.netPnl,-2);assert.equal(result.daily[1].cash,99);
assert.equal(simulateTrade(bars,0,{coverageVerified:true,pointInTimeVerified:true},{brokerProfile:'ibkr-fixed'}).status,'blocked');
assert.deepEqual(JSON.parse(html.match(/const UI_BROKER_PROFILES=(.*);/)[1]),BROKER_PROFILES);
console.log('Verified broker catalog: source consistency, per-share/minimum/cap, whole-share cash and strict historical tariff block.');

