// Evidence projection only: endpoint access is distinct from data qualification.
export const CAPABILITY_VERSION='data-capabilities-v1';
export function dataCapabilities(records=[]){
 const definitions=[['rawPrices','time_series','none','values'],['adjustedPrices','time_series','all','values'],['splits','splits',null,'splits'],['dividends','dividends',false,'dividends']];
 const sources=definitions.map(([kind,endpoint,adjust,field])=>{
  const matched=records.filter(r=>r.provenance?.source==='Twelve Data /'+endpoint&&(adjust===null||r.provenance?.parameters?.adjust===adjust));
  const observations=matched.map(r=>({symbol:r.symbol||r.provenance?.parameters?.symbol||null,snapshotId:r.snapshotId||null,accessStatus:r.accessStatus|| (r.payload||r.pricePayload?'observed':r.error?'failed':'unknown'),shapeStatus:Array.isArray((r.payload||r.pricePayload)?.[field])?'observed':'unknown',rowCount:Array.isArray((r.payload||r.pricePayload)?.[field])?(r.payload||r.pricePayload)[field].length:null,period:r.provenance?.period||null,requestedPeriod:{from:r.provenance?.parameters?.start_date||null,to:r.provenance?.parameters?.end_date||null},retrievedAt:r.provenance?.retrievedAt||null,publicationTime:r.provenance?.publicationTime||null,availableAt:r.provenance?.availableAt||null,historicalVintage:r.provenance?.historicalVintage||null,archiveStatus:r.archived?'saved':'unknown',qualityStatus:r.quality?r.quality.usable?'usable':'blocked':'not-checked',httpStatus:r.provenance?.httpStatus||null,error:r.error||null}));
  return {kind,endpoint,adjust,accessStatus:!observations.length||observations.every(r=>r.accessStatus==='not-checked')?'not-checked':observations.every(r=>r.accessStatus==='observed'&&r.shapeStatus==='observed')?'observed':'incomplete',observations,coverageStatus:'unknown',costStatus:'account-entitlement-not-checked',historicalAvailabilityStatus:'unknown'};
 });
 const gate=(reasons)=>({status:'blocked',reasons});
 return {version:CAPABILITY_VERSION,sources,calendar:{source:'https://www.nyse.com/trade/hours-calendars',version:'us-core-2021-2027-20261004',supportedYears:[2021,2027],historicalQualification:'limited-before-2025',unexpectedClosures:'unknown'},archive:{status:records.length&&records.every(r=>r.archived)?'snapshots-saved':'not-checked',liveConditionalWriteAcceptance:'not-checked',licenseStatus:'not-checked'},actions:{splits:'coverage-unknown',dividends:'coverage-unknown',otherActions:'unknown'},gates:{retrospectiveCostScenario:gate(['raw-price-qualification-required','complete-action-coverage-not-evidenced','execution-and-cost-acceptance-required']),historicalModelValidation:gate(['historical-vintages-and-availability-not-evidenced','qualified-calendar-and-purged-evaluation-required']),empiricalForecastQuality:gate(['untouched-prospective-test-not-evaluated','baseline-comparison-and-uncertainty-not-evaluated'])},phase1:{technicalPreparation:'implemented',dataAcceptance:'not-checked',realNetRelease:'blocked',forecastRelease:'blocked',prospectiveCollection:'explicit-post-required'}};
}
